Repository PMEAL/porespy, pull requests merged in 2020-08, with the labels that each got.

#291 Replace pep8 with pycodestyle
  .github/workflows/ci-macos.yml
  .github/workflows/ci-min.yml
  .github/workflows/ci-ubuntu.yml
  .github/workflows/ci-windows.yml
  porespy/generators/__imgen__.py
  porespy/networks/__funcs__.py
  porespy/tools/__funcs__.py
  pytest.ini
  requirements/test_requirements.txt
  setup.cfg
Labels: bug, high priority

#293 Fully automating the deployment via GitHub Actions
  .github/workflows/bump-version.yml
  .github/workflows/ci-macos.yml
  .github/workflows/ci-windows.yml
  .github/workflows/cleanup-tags.yml
  .github/workflows/logger.sh
  .github/workflows/publish-to-pypi.yml
  .github/workflows/release-notes.yml
  .travis.yml
  codecov.yml
  porespy/__init__.py
  porespy/__version__.py
  pytest.ini
  requirements/conda_requirements.txt
  requirements/test_requirements.txt
  setup.py
Labels: enhancement, low priority

#288 SNOW_partitioning_parallel
  .coveragerc
  examples/filters/snow_partitiioning_parallel.ipynb
  porespy/filters/__funcs__.py
  porespy/filters/__init__.py
  test/unit/test_filters.py
Labels: enhancement
